[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
dependsOn = ['setup']
cmds = [
  'pnpm install --frozen-lockfile'
]

[phases.build]
dependsOn = ['install']
cmds = [
  'pnpm run build'
]
cacheDirectories = ['.next/cache', 'node_modules/.cache']

[start]
cmd = 'pnpm start'

[variables]
NODE_ENV = 'production'
